### PR TITLE
Mention LGPL and fix Travis CI

### PR DESCRIPTION
**Pull request by hosamaly**
This PR [fixes the build in Travis CI](https://travis-ci.org/hosamaly/scala-xml-diff/builds/350296790). Passing Build

In addition, it includes the following changes:
* Add LGPL to the list of licenses in sbt (already added to the project in `COPYING.LESSER`)
* Upgrade scala versions, sbt, and dependencies, except for the scala-xml dependency lest it forces an upgrade on library users.

### CODE REVIEW

**Comment by andyglow** [comment]
that's cool!
thanks a lot
accepting

**Comment by hosamaly** [comment]
That's great, @andyglow. Thank you!

Would you be able to release a new version and publish it for both versions of Scala?

**Comment by andyglow** [comment]
Done
http://repo1.maven.org/maven2/com/github/andyglow/scala-xml-diff_2.11/2.0.3/
http://repo1.maven.org/maven2/com/github/andyglow/scala-xml-diff_2.12/2.0.3/

**Comment by hosamaly** [comment]
That's great. Thanks, Andy!

**Pull request merged**
